COMPONENT=SaWAppC
TINYOS_ROOT_DIR?=../tinyos-main
TINYOS_NO_DEPRECATION_WARNING?=1 # Telosb uses the older build system. Surpressing warning.
CFLAGS += -DCC2420_DEF_RFPOWER=10 # 1 (lowest) - 31 (highest)
include $(TINYOS_ROOT_DIR)/Makefile.include
